codecov:
  notify:
    after_n_builds: 3

coverage:
  status:
    project:
      default:
        informational: false
      linux:
        flags:
          - linux
      macos:
        flags:
          - macos
      windows:
        flags:
          - windows

flags:
  linux:
    paths:
      - src/
  macos:
    paths:
      - src/
  windows:
    paths:
      - src/
